### ISSUE TITLE
Nano-calc v2

### ISSUE THREAD

**Issue by jack-williams** [microsoft/tiny-calc#41]
Items for the next iteration of `nano`.
- [x] Quoted field names like `A.{Foo Bar Baz}` #42
- [ ] Named subexpressions with preview capability like http://tomasp.net/academic/drafts/live/live.pdf.
- [x] Tree-based interpreter. #44
- [x] Tracing and effects refactor. #43 
- [x] Better error handling. #44
- [x] Build out more examples. #45
- [x] First cut and explicit API for core properties like `value` and `stringify`. #43 (more work to be done).

**Comment by jack-williams** [comment]
Shelving live preview for now as I plan to look at incremental computation instead!
